- README.md
The example action wasn't working when using `context.issue`, `context.owner` and `context.repo`. This PR changes it to use `context.issue.number`, `context.repo.owner` and `context.repo.repo`, which seems to fix it.
> Fix example context properties

- action.yml
With the system side changes to support `actions/checkout@v2`, some of the `github` context can now be used in the action.yml file as defaults, including the GitHub token.
This removes the need for the user to specify the GitHub token as input for *most* cases.
[Workflow](https://github.com/joshmgross/github-script-testing/blob/master/.github/workflows/%F0%9F%91%8B.yml)
[Sample Issue](https://github.com/joshmgross/github-script-testing/issues/2)
Let me know if you want me to update the examples in the README.md, it might be worth having at least one example using a token.
> Default to the GitHub token

- README.md
Both ways should be valid, but the regular nested YAML keys seems to be the format of the regular GitHub Actions docs
> fix: Example YAML schema to match Actions Docs

- README.md
These references shouldn't use the `@actions` syntax, which is for the npm `@actions` packages.
cc @jclem
> Fix Action references in separate file example

- dist/index.js
- package-lock.json
- package.json
This adds @octokit/* packages as direct dependencies of this Action.
Previously, when they were transitive, we had to wait for @actions/toolkit to update in order to get those new versions. As long as the direct dependencies we have are compatible with what @actions/toolkit needs, they'll be used, instead.
Fixes https://github.com/actions/github-script/issues/58
> Add Octokit deps directly

- README.md
An absolute path is required when calling `require()` from within the github-script's script in the workflow YAML.
This PR adds a note for this in the ["Run a separate file"](https://github.com/actions/github-script#run-a-separate-file) section of the readme.
> Adds note that absolute path is required

- README.md
- update example for using `GITHUB_WORKSPACE` environment variable to keep things simple, and use less steps
- include `github` object as a parameter to the sample script to better illustrate usage
> docs: use GITHUB_WORKSPACE environment variable

- README.md
This makes the version of github-script used in the 'View context attributes' example consistent with the version used by all of the other examples in the README.
> Use @v3 in 'View context attributes' example

- README.md
Hi! 
$label was not defined as input argument, and it was throwing and error.
Also updated job name to reflect what it actually does.
> Fix typo in Readme example

- .github/workflows/pull-request-test.yml
I accidentally removed two lines I did not intend to. This would only
break for PRs opened on the repo directly.
> Fix typo from #117

- README.md
ℹ️  Updated to document `env` and `process.env` as inputs. 
---
We've been using `actions/github-script` to glue together different build tools. We've had cases where we want to passthrough outputs of other scripts to this action –
- One way would be to just use an input value:
```yaml
- uses: actions/github-script@v3
with:
foo: 'bar'
script: console.log(core.getInput('foo'))
```
which works, but displays this warning:
```
Warning: Unexpected input(s) 'foo', valid inputs are ['script', 'github-token', 'debug', 'user-agent', 'previews', 'result-encoding']
```
- Another way would be to inline the value:
```yaml
- uses: actions/github-script@v3
with:
script: console.log('${{ 'foo' }}')
```
but this can cause issues depending on what the value of the string is, and requires you to be aware of …
> Document how to use npm packages and env input

- .licenses/npm/@actions/glob.dep.yml
- .licenses/npm/balanced-match.dep.yml
- .licenses/npm/brace-expansion.dep.yml
- .licenses/npm/concat-map.dep.yml
- .licenses/npm/minimatch.dep.yml
- README.md
- dist/index.js
- package-lock.json
- package.json
- src/async-function.ts
- src/main.ts
The `@actions/glob` package is useful for any scripts doing file manipulation. This package is now available to the script using the `glob` variable.
> Add @actions/glob as a script parameter

- README.md
Hello,
It took me a few tries to have **github-script** run a separate file with async/await, so as suggested [in this issue](https://github.com/actions/github-script/issues/115), I went ahead and opened this PR to add an example in the readme.
It may save some time to others.
Please let me know if I'm missing something.
Cheers
> Update readme with async example

- README.md
Hi there, thanks for this project!
It seems like the `octokit/rest.js` documentation would be better to link to here, since it shows the methods that are used in the readme.
> Link to better octokit docs

- .github/workflows/integration.yml
- README.md
- dist/index.js
- package.json
- src/async-function.ts
- src/main.ts
- src/wrap-require.ts
- types/non-webpack-require.ts
This adds support for the following:
- Requiring modules by a path relative to the working directory `require('./foo')` 
- Requiring npm modules installed in the working directory `require('lodash')`
This is accomplished by wrapping the `require` passed to the script in a proxy.
- When the script calls `require` with a path that starts with `'.'`, we transform that module ID to the result of `path.join(process.cwd(), moduleID)` and then require the absolute path, instead.
- When a script calls `require` for some non-relative path and an error is thrown, we catch that error and try again, this time adding `process.cwd()` to the list of paths searched-through.
Thanks to @joshmgross and @wraithgar for doing the real work here 😄
> Support installed npm modules and relative require

- dist/index.js
- package.json
- src/wrap-require.ts
Currently, we search the existing `module.paths` and _then_ `process.cwd()` when a user script calls `require`. Instead, we should remove the fallback altogether (since at runtime, the actions/github-script directory has no modules installed, anyway), and only search `process.cwd()`.
This can be a patch release once merged.
Thanks @JamesMGreene [for reporting](https://github.com/actions/github-script/pull/135#discussion_r617914537).
> Only search cwd on user-script require calls

- .licenses/npm/@actions/core.dep.yml
- dist/index.js
- package-lock.json
- package.json
This updates `@actions/core` to 1.2.7 and updates this action's version to 4.0.2
> Update @actions/core to 1.2.7

- README.md
> docs: remove `github-token` usage from examples

- README.md
#145 removed the `github-token` usage in the examples so that users could copy and paste the examples without any extra configuration.
Most users will not need a separate GitHub token and the previous example of `secrets.GITHUB_TOKEN` was not a valid secret name, so some modification was always required.
This PR adds a new example so that users know how to provide their own GitHub token.
> Add instructions for using a separate GitHub token

- README.md
I didn't realise `require` was a custom wrapper so I changed the read me to make it more obvious, but I'm happy to change the wording if this is still not clear or if is badly worded
> Make it clear that require is a custom wrapper

- README.md
Closes #168
With #235 and the update to Node 16, users should be able to use ESM files with `import`. This PR adds an example detailing what's required for that.
> Add an example using ESM `import`

- .licenses/npm/@actions/github.dep.yml
- __test__/get-retry-options.test.ts
- dist/index.js
- package-lock.json
- package.json
- src/main.ts
- src/retry-options.ts
Since introducing retries in #288, we would override the `request` field of the `OctokitOptions` we pass into the `getOctokit` method. The problem is that the `@actions/github` package also provides some defaults for the `request` field. [source](https://github.com/actions/toolkit/blob/4fbc5c941a57249b19562015edbd72add14be93d/packages/github/src/utils.ts#L15). Some users rely on these defaults and would break since we added retries.
Behavior: 
If we have these defaults:
```js
{
request: {
agent: 'some-agent'
}
}
```
and add these options: 
```js
{
request: {
retries: 2
}
}
```
we get the following output: 
```js
{
request: {
retries: 2
}
}
```
Note the original options are completely overriden, which is not desired. 
We copy the default `options.request` fields from the `@actions/github` …
> Fix overriding request options from @actions/github

- .licenses/npm/@actions/core.dep.yml
- dist/index.js
- package-lock.json
- package.json
This updates @actions/core to use the [file version](https://github.com/actions/toolkit/pull/1178) of `save-state` and
`set-output` workflow commands.
> Update @actions/core to 1.10.0

- .github/workflows/check-dist.yml
- .github/workflows/ci.yml
- .github/workflows/integration.yml
- .github/workflows/licensed.yml
- .github/workflows/pull-request-test.yml
- README.md
Update actions/checkout, actions/setup-node, actions/cache, and actions/upload-artifact from v2 to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
> Update GitHub actions packages

- .github/workflows/check-dist.yml
- .github/workflows/ci.yml
- README.md
- dist/index.js
Closes https://github.com/actions/github-script/issues/337
It looks like this has been failing since #320, so I'm guessing some change from updating `minimatch` should've been reflected in the `dist` but wasn't.
I've also gone ahead and updated our CI workflows to use Node 16, matching the version of Node used by this action.
> Regenerate `dist`

- .licenses/npm/minimatch.dep.yml
#320 updated `minimatch` but the license wasn't updated, breaking that CI build.
This should fix it.
> Update license for minmatch

- package-lock.json
- package.json
Preparing to release v6.4.0 which will include `node-fetch` - #321
> Bump version to 6.4.0

- package-lock.json
- package.json
As part of #349 we updated the version to `4.1.0`, but we already had `4.1.0` and for `4.1.1`. This bumps version to `4.2.0`.
> Prepare release v4.2.0

- .licenses/npm/@octokit/plugin-request-log.dep.yml
- dist/index.js
- package-lock.json
- package.json
- src/main.ts
Without this plugin, the debug setting is, effectively, meaningless as
none of the existing plugins produce log output.
The plugin writes the request options to octokit.log.debug, and response
times as *method path - status in ...ms* to octokit.log.info.
Fixes #265
> Add @octokit/plugin-request-log, to produce debug output for requests

- .eslintrc.yml
- .github/workflows/integration.yml
- dist/index.js
- src/main.ts
- src/retry-options.ts
- tsconfig.eslint.json
This PR fixes how github-script handles the inputs given, which in turn
unbreaks how the Octokit request defaults are set.
I've included an extra ESLint rule to guard against the error in future, as
well as expanded the integration tests to cover action settings better.
- Clean and spruce up the integration tests a bit
- Use test-specific step ids
- Remove unused input parameters
- Provide clear output on what passed or failed, including a step summary for each passed test.
- Fix null handling, covered by integration tests
- `core.getInput()` always returns a string, so testing for 'not null' is always true. This then leads to previews set to an array with a single empty string, breaking accept-header output.
- Updated eslint rules should help avoid this issue in future, and new …
> fix input handling

- .github/workflows/integration.yml
- action.yml
When the action 'debug' input is not set, default to the current runner debug state. This ensures that the Octokit client request logs are included automatically when you re-run a job with debug enabled.
Note that the integration test for the 'debug' option is now a matrix test, to cover both the runner debug mode being disabled and enabled; you have to set the `RUNNER_DEBUG` env variable in a separate step because `step.<step-id>.env` is evaluated *after* any action `with:` block.
Fixes #264
> Default debug to current runner debug state

- .github/workflows/check-dist.yml
This workflow is a required status check, so we can't skip running it.
This is preventing #285 from merging
> Remove path filters from check-dist workflow

- .github/ISSUE_TEMPLATE/config.yml
For general feedback or questions, we should direct users to a more appropriate place than an issue.
This is similar to the template used by https://github.com/actions/languageservices
> Add more issue templates

- .github/workflows/integration.yml
- dist/index.js
- src/main.ts
Fixes #436 
Replaces #437
Due to how options are passed through `@actions/github` to Octokit, an `undefined` `baseUrl` prevents the default from being used. This breaks using github-script on GHES, which requires the GHES instance API URL.
#437 attempted to reproduce this issue in a test, but it was unsuccessful. There's a similar issue in the integration test, but the fix doesn't work despite it being confirmed in https://github.com/actions/github-script/issues/436#issuecomment-1816670425.
I've included the other integration tests, but they don't cover this specific scenario or what we're trying to fix.
> Avoid setting `baseUrl` to undefined when input is not provided

- .husky/pre-commit
- package-lock.json
- package.json
Migrate to husky v9 following the instructions in their [release notes](https://github.com/typicode/husky/releases/tag/v9.0.1).
For context, I got the following husky error when [installing this package for JSDoc support](https://github.com/actions/github-script?tab=readme-ov-file#use-scripts-with-jsdoc-support):
```logs
❱ npm i -D @types/github-script@github:actions/github-script
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command npm install --force --cache=/home/****/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! > github-script@7.0.1 prepare
npm ERR! > husky install
npm ERR! npm WARN using --force Recommended protections …
```
> Upgrade husky to v9

- README.md
The current status badge URLs show an incorrect status:
[![.github/workflows/integration.yml](https://github.com/actions/github-script/workflows/Integration/badge.svg?event=push&branch=main)](https://github.com/actions/github-script/actions?query=workflow%3AIntegration+branch%3Amain+event%3Apush)
[![.github/workflows/ci.yml](https://github.com/actions/github-script/workflows/CI/badge.svg?event=push&branch=main)](https://github.com/actions/github-script/actions?query=workflow%3ACI+branch%3Amain+event%3Apush)
[![.github/workflows/licensed.yml](https://github.com/actions/github-script/workflows/Licensed/badge.svg?event=push&branch=main)](https://github.com/actions/github-script/actions?query=workflow%3ALicensed+branch%3Amain+event%3Apush)
I generated new URLs from the "Create status badge" …
> Fix workflow status badges

- .github/workflows/check-dist.yml
v3 is deprecated, let's use the latest and greatest!
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Update usage of `actions/upload-artifact`

- .github/workflows/integration.yml
- README.md
- package-lock.json
- package.json
- #500 
- https://github.com/advisories/GHSA-v9m5-8c6w-p3m5
This repository is *not* the `github-script` package that's been identified as malware and it has never been published to the NPM registry.
Installing this repository as a repository package via NPM warns about this vulnerability due to the `package.json` name `github-script`. To clear up confusion, I've changed this name to `@actions/github-script` which is under our controlled Actions NPM [scope](https://docs.npmjs.com/about-scopes).
> Clear up package name confusion

- README.md
At first, it was unclear to me that the script provided was in JavaScript. I'm suggesting this change to make this clear from the start.
> Specify that the used script is JavaScript

- .github/dependabot.yml
Few of the built-in actions are behind by one major. Seems like only the Dependabot Security PRs are being sent right now
> chore: Add Dependabot for NPM and Actions

- README.md
- #545
#508 introduced a new `octokit` variable to make it easier to use examples from GitHub and Octokit docs within `actions/github-script`.
That change *is* a breaking change so the README updates shouldn't have been made with v7.
We'll update the README to include this info again when we're ready for v8 - #556
> Remove `octokit` README updates for v7

- README.md
Add basic usage example for "exec" package into github-script action context
> docs: add "exec" usage examples

- README.md
A lot of questions we get around `SyntaxError`s are due to misusing Actions Expressions with the `script` - https://github.com/actions/github-script/issues?q=is:issue%20state:closed%20SyntaxError 
- #220
- #401
- #567
- #597
This was documented in #126, but I believe it's worth clearly highlighting the [security risks](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections) of using Actions expressions within the `script` and moving it up in the README as it's a common scenario.
> Clearly document passing inputs to the `script`
